const APP_DATA = {
  telefon: [
    { id: 't1', text: 'Sakin karşıla; Kıdemli İş Analisti (EBYS/DYS/E-İmza) pozisyonunu teyit et' },
    { id: 't2', text: 'Görüşme için uygun zaman sor; müsait değilsen geri arama saati belirle' },
    { id: 't3', text: '3+ yıl EBYS/DYS/E-İmza deneyiminizi kısaca özetlemeye hazır ol' },
    { id: 't4', text: 'Ankara ofis / çalışma modeli (ofis/hibrit) konusunu netleştir' },
    { id: 't5', text: 'Görüşme tarihini takvime ekle, hatırlatıcı kur' },
    { id: 't6', text: 'İK\'ya teşekkür et, iletişim bilgilerini not al' },
  ],

  'ik-oncesi': [
    { id: 'ik1', text: 'İnnova araştırması: Türk Telekom Grubu, kamu/kurumsal EBYS projeleri' },
    { id: 'ik2', text: '"Neden bu pozisyon?" — EBYS/DYS alanındaki deneyim ve motivasyonunuzu 3 maddede hazırlayın' },
    { id: 'ik3', text: 'EBYS, DYS, E-İmza ve KEP projelerinizden her biri için 1 dk özet hazırlayın' },
    { id: 'ik4', text: 'Kamu kurumu veya büyük ölçekli kurumsal proje deneyiminizi vurgulayın' },
    { id: 'ik5', text: 'UAT yönetimi ve kullanıcı eğitimi deneyiminize örnek hazırlayın' },
    { id: 'ik6', text: 'Soracağınız 3 soru: proje portföyü, ekip yapısı, EBYS ürün/teknoloji stack\'i' },
    { id: 'ik7', text: 'İngilizce kendinizi tanıtma pratiği (2 dk)' },
  ],

  'teknik-hazirlik': [
    { id: 'th1', text: 'EBYS/DYS süreç akışını (belge oluşturma → onay → arşivleme) anlatabilir ol' },
    { id: 'th2', text: 'E-İmza türlerini bil: Nitelikli, Mobil, Zaman Damgası, Mali Mühür' },
    { id: 'th3', text: 'KEP (Kayıtlı Elektronik Posta) entegrasyon sürecini ve yasal çerçeveyi özetle' },
    { id: 'th4', text: 'GTD (Gereksinim Tanımları Dokümanı) örneğini hazır bulundur' },
    { id: 'th5', text: 'BPMN ile iş akışı diyagramı çizme pratiği (onay süreçleri, vekalet, red akışı)' },
    { id: 'th6', text: 'UML: Use Case, Activity Diagram, Sequence Diagram örneklerini gözden geçir' },
    { id: 'th7', text: 'Mockup/Wireframe örneği hazırla (belge yükleme, onay ekranı, arama)' },
    { id: 'th8', text: 'SQL ile veri doğrulama örneği: belge sayısı, onay süresi, durum sorguları' },
    { id: 'th9', text: 'Agile/Scrum + Jira/Confluence kullanım deneyimini somutlaştır' },
    { id: 'th10', text: 'Entegrasyon dokümanı inceleme ve gereksinim uygunluk değerlendirme örneği' },
  ],

  'mulakat-gunu': [
    { id: 'mg1', text: 'Kurumsal kıyafet, kamera görüşmesi için üst kısım düzenli' },
    { id: 'mg2', text: '15 dk erken bağlan, internet ve mikrofon testi yap' },
    { id: 'mg3', text: 'GTD, BPMN, Use Case örnekleri açık sekmede beklesin' },
    { id: 'mg4', text: 'EBYS/DYS terimler sözlüğünü yanında bulundur (EBYS, DYS, KEP, GTD, UAT)' },
    { id: 'mg5', text: 'Her cevapta STAR yöntemini kullan' },
    { id: 'mg6', text: 'Teknik sorularda: gereksinim → süreç → doküman → test zincirini göster' },
    { id: 'mg7', text: 'Sonunda teşekkür et, sonraki adımı ve süreyi sor' },
  ],

  sabah: [
    { id: 's1', text: 'Jira backlog ve Confluence doküman güncellemelerini kontrol et' },
    { id: 's2', text: 'Stand-up: dünkü analiz çıktıları, bugünkü paydaş görüşmeleri, engeller' },
    { id: 's3', text: 'Açık gereksinim değişiklik taleplerini (CR) gözden geçir' },
    { id: 's4', text: 'Bugünkü UAT veya kullanıcı eğitimi hazırlıklarını kontrol et' },
  ],

  ogle: [
    { id: 'o1', text: 'Müşteri/paydaş görüşmeleri: EBYS/DYS ihtiyaç analizi' },
    { id: 'o2', text: 'İş akışı diyagramı ve süreç modeli güncelleme (BPMN)' },
    { id: 'o3', text: 'GTD, Use Case, User Story ve iş kuralları dokümantasyonu' },
    { id: 'o4', text: 'Geliştirme ekibiyle backlog refinement — entegrasyon gereksinimleri' },
  ],

  'ogleden-sonra': [
    { id: 'os1', text: 'Teknik çözüm dokümanı ve entegrasyon dokümanı inceleme (KEP, E-İmza API)' },
    { id: 'os2', text: 'UAT senaryoları hazırlama veya UAT oturumuna katılım' },
    { id: 'os3', text: 'Mockup/Wireframe güncelleme — ekran tasarımı revizyonları' },
    { id: 'os4', text: 'SQL ile veri doğrulama: belge durumları, entegrasyon logları' },
  ],

  'gun-sonu': [
    { id: 'gs1', text: 'Confluence\'a günün analiz çıktılarını ve kararları yaz' },
    { id: 'gs2', text: 'Jira\'da görev durumlarını güncelle, açık aksiyonları ata' },
    { id: 'gs3', text: 'Yarınki paydaş toplantısı için gündem ve soru listesi hazırla' },
    { id: 'gs4', text: 'Canlıya geçiş veya test sürecindeki riskleri PM\'e ilet' },
  ],

  temelYetkinlikler: [
    { id: 'ty1', text: 'Üniversite mezuniyeti (ilgili bölüm)' },
    { id: 'ty2', text: '3+ yıl EBYS, DYS ve E-İmza alanında iş analisti deneyimi' },
    { id: 'ty3', text: 'Gereksinim yönetimi ve yazılım geliştirme yaşam döngüsü deneyimi' },
    { id: 'ty4', text: 'KEP entegrasyonları ve elektronik belge paylaşım süreçleri deneyimi' },
    { id: 'ty5', text: 'Agile/Scrum bilgisi + Jira, Confluence kullanımı' },
    { id: 'ty6', text: 'BPMN ve UML (Use Case, Activity, Sequence) modelleme' },
    { id: 'ty7', text: 'Mockup/Wireframe hazırlama becerisi' },
    { id: 'ty8', text: 'SQL ile temel veri analizi ve veri doğrulama' },
    { id: 'ty9', text: 'Teknik ekiplerle etkin iletişim ve teknik analiz' },
    { id: 'ty10', text: 'Analitik düşünme, problem çözme, iletişim becerileri' },
  ],

  tercihYetkinlikler: [
    { id: 'tr1', text: 'EBYS, DYS, E-İmza, KEP veya dijital belge yönetimi projeleri' },
    { id: 'tr2', text: 'Kamu kurumları veya büyük ölçekli kurumsal proje analiz deneyimi' },
    { id: 'tr3', text: 'Doküman yönetimi, iş akışı ve süreç yönetimi bilgisi' },
    { id: 'tr4', text: 'UAT süreç yönetimi ve kullanıcı eğitimi deneyimi' },
  ],

  sorumluluklar: [
    { id: 'sr1', text: 'Müşteri ihtiyaçlarını analiz et, fonksiyonel ve fonksiyonel olmayan gereksinimleri belirle' },
    { id: 'sr2', text: 'İş süreçlerini analiz et, süreç iyileştirme önerileri geliştir' },
    { id: 'sr3', text: 'Gereksinimlerin teknik ekiplerce doğru anlaşılmasını sağla, analiz süreçlerini yönet' },
    { id: 'sr4', text: 'İş akış diyagramları, süreç modelleri, Use Case, User Story ve iş kuralları oluştur' },
    { id: 'sr5', text: 'GTD, analiz dokümanları ve iş kuralları dokümanlarını hazırla' },
    { id: 'sr6', text: 'Teknik çözüm dokümanları, veri modelleri ve entegrasyon dokümanlarını incele' },
    { id: 'sr7', text: 'UAT planlama ve yürütme süreçlerinde aktif rol al' },
    { id: 'sr8', text: 'Kullanıcı eğitimleri ver, kullanıcı dokümantasyonlarını hazırla' },
    { id: 'sr9', text: 'Analiz, geliştirme, test ve canlıya geçiş süreçlerinde ekiplerle koordineli çalış' },
  ],

  starScenarios: [
    { id: 'star1', title: 'EBYS/DYS proje deneyimi', placeholder: 'Örn: X kurumunun EBYS geçiş projesinde 500+ kullanıcılı belge yönetim sürecini analiz ettim...' },
    { id: 'star2', title: 'E-İmza entegrasyonu', placeholder: 'Örn: Nitelikli e-imza entegrasyonunda imza doğrulama ve zaman damgası gereksinimlerini tanımladım...' },
    { id: 'star3', title: 'KEP entegrasyon süreci', placeholder: 'Örn: KEP entegrasyonunda gönderim/alım akışı, delil raporu ve yasal uyumluluk gereksinimlerini belirledim...' },
    { id: 'star4', title: 'UAT yönetimi', placeholder: 'Örn: 200 kullanıcılı UAT sürecini planladım, senaryo hazırladım, hata takibini yönettim...' },
    { id: 'star5', title: 'Kamu kurumu projesi', placeholder: 'Örn: Kamu kurumunun dijital belge yönetimi projesinde mevzuat uyumlu süreç tasarladım...' },
    { id: 'star6', title: 'Süreç iyileştirme', placeholder: 'Örn: Manuel onay sürecini dijitalleştirerek onay süresini 5 günden 1 güne indirdik...' },
    { id: 'star7', title: 'Kullanıcı eğitimi', placeholder: 'Örn: 150 kullanıcıya EBYS eğitimi verdim, kullanım kılavuzu ve video içerik hazırladım...' },
    { id: 'star8', title: 'Entegrasyon dokümanı inceleme', placeholder: 'Örn: KEP API entegrasyon dokümanını inceledim, gereksinimlere uygunluk analizi yaptım...' },
  ],

  interviewQuestions: [
    {
      q: 'EBYS ile DYS arasındaki fark nedir?',
      a: 'EBYS (Elektronik Belge Yönetim Sistemi): belgelerin elektronik ortamda oluşturulması, onaylanması, saklanması ve imha edilmesi. DYS (Doküman Yönetim Sistemi): daha geniş kapsamda doküman versiyonlama, erişim kontrolü, metadata yönetimi. EBYS genelde DYS\'in bir alt kümesi veya kamu mevzuatına uyumlu özel versiyonudur.',
    },
    {
      q: 'E-İmza türlerini ve kullanım alanlarını açıklayın.',
      a: 'Nitelikli E-İmza (5070 sayılı kanun, hukuki geçerlilik), Mobil İmza, Mali Mühür (kurumsal), Zaman Damgası. EBYS\'de belge onayı, KEP gönderiminde kimlik doğrulama, sözleşme imzalama gibi alanlarda kullanılır.',
    },
    {
      q: 'KEP entegrasyonu nasıl çalışır?',
      a: 'Kayıtlı Elektronik Posta: yasal delil niteliği taşıyan e-posta. Entegrasyon: KEPHS (KEP Hizmet Sağlayıcı) API\'si üzerinden gönderim/alım, delil raporu oluşturma, gönderi takibi. EBYS ile entegrasyonda belge KEP üzerinden paylaşılır, delil saklanır.',
    },
    {
      q: 'EBYS\'de tipik bir belge yaşam döngüsü nasıldır?',
      a: 'Oluşturma → Taslak → Onay akışı (sıralı/paralel) → İmzalama (e-imza) → Yayınlama/Arşivleme → Saklama süresi → İmha. Her aşamada yetki kontrolü, log kaydı ve versiyon yönetimi.',
    },
    {
      q: 'GTD (Gereksinim Tanımları Dokümanı) nasıl hazırlanır?',
      a: 'Giriş/kapsam → Paydaşlar → Fonksiyonel gereksinimler (FR) → Fonksiyonel olmayan gereksinimler (NFR) → İş kuralları → Ekran gereksinimleri → Entegrasyon gereksinimleri → Kabul kriterleri → Traceability matrix',
    },
    {
      q: 'BPMN ile iş akışı modellemesini nasıl yaparsınız?',
      a: 'AS-IS süreç analizi → darboğaz tespiti → TO-BE süreç tasarımı. Gateway (XOR, AND, OR), Lane (rol/departman), Event (başlangıç/bitiş), Task (kullanıcı/servis). Onay/red/vekalet akışları modellenir.',
    },
    {
      q: 'UAT sürecini nasıl yönetirsiniz?',
      a: 'UAT planı → Senaryo hazırlama (iş akışı bazlı) → Test verisi → Kullanıcı seçimi → Oturum yönetimi → Hata kaydı (Jira) → Düzeltme takibi → Kabul imzası → Canlıya geçiş onayı',
    },
    {
      q: 'SQL ile veri doğrulama nasıl yaparsınız?',
      a: 'Belge durum sorguları (taslak/onaylı/arşiv), onay süresi analizi, entegrasyon log kontrolü, kullanıcı aktivite raporları. Örn: SELECT durum, COUNT(*) FROM belgeler GROUP BY durum',
    },
    {
      q: 'Kamu kurumu EBYS projelerinde dikkat edilmesi gerekenler?',
      a: '5018 sayılı kanun, 5070 sayılı e-imza kanunu, 4982 sayılı bilgi edinme, arşiv mevzuatı, KVKK, saklama ve imha süreleri, yetki matrisi, denetim izi (audit trail).',
    },
    {
      q: 'Gereksinim değişikliği (CR) nasıl yönetilir?',
      a: 'Talep kaydı → Etki analizi (süreç, entegrasyon, ekran, test) → Paydaş onayı → GTD güncelleme → Jira backlog güncelleme → Geliştirme/test koordinasyonu',
    },
  ],

  weekFocus: [
    { day: 'Pazartesi', focus: 'Sprint planlama, paydaş görüşmeleri, açık CR değerlendirmesi' },
    { day: 'Salı', focus: 'GTD ve iş kuralları dokümantasyonu, BPMN süreç modelleri' },
    { day: 'Çarşamba', focus: 'Geliştirme ekibi backlog refinement, entegrasyon gereksinimleri' },
    { day: 'Perşembe', focus: 'UAT senaryoları, mockup revizyonları, teknik doküman inceleme' },
    { day: 'Cuma', focus: 'Kullanıcı eğitimi hazırlığı, haftalık özet, Confluence güncelleme' },
  ],

  skills: [
    {
      id: 'ebys',
      name: 'EBYS (Elektronik Belge Yönetim Sistemi)',
      priority: 'kritik',
      tools: ['OpenText', 'Alfresco', 'Logo EBYS', 'Luca'],
      topics: ['Belge yaşam döngüsü', 'Onay akışları', 'Arşivleme', 'Mevzuat uyumu', 'Audit trail'],
      resources: ['5070 sayılı E-İmza Kanunu', 'Devlet Arşivleri mevzuatı'],
    },
    {
      id: 'dys',
      name: 'DYS (Doküman Yönetim Sistemi)',
      priority: 'kritik',
      tools: ['SharePoint', 'Documentum', 'M-Files'],
      topics: ['Versiyon kontrolü', 'Metadata', 'Erişim yetkileri', 'Tam metin arama', 'Klasör yapısı'],
      resources: ['AIIM DMS best practices'],
    },
    {
      id: 'eimza',
      name: 'E-İmza Çözümleri',
      priority: 'kritik',
      tools: ['E-Güven', 'TÜRKTRUST', 'Kamu SM', 'Mali Mühür'],
      topics: ['Nitelikli e-imza', 'Mobil imza', 'Zaman damgası', 'İmza doğrulama', 'HSM entegrasyonu'],
      resources: ['5070 sayılı kanun', 'BTK e-imza rehberleri'],
    },
    {
      id: 'kep',
      name: 'KEP (Kayıtlı Elektronik Posta)',
      priority: 'kritik',
      tools: ['PTT KEP', 'TÜRKKEP', 'TURKCELL KEP', 'KEPHS API'],
      topics: ['Gönderim/alım akışı', 'Delil raporu', 'Entegrasyon API', 'Yasal geçerlilik'],
      resources: ['KEP Yönetmeliği', 'KEPHS teknik dokümanları'],
    },
    {
      id: 'bpmn',
      name: 'BPMN İş Akışı Modelleme',
      priority: 'kritik',
      tools: ['Bizagi Modeler', 'draw.io', 'Camunda', 'Visio'],
      topics: ['AS-IS / TO-BE', 'Onay akışları', 'Gateway', 'Lane/Rol', 'Vekalet süreçleri'],
      resources: ['https://www.bpmn.org/', 'Bizagi eğitim videoları'],
    },
    {
      id: 'uml',
      name: 'UML Modelleme',
      priority: 'kritik',
      tools: ['draw.io', 'Enterprise Architect', 'Lucidchart'],
      topics: ['Use Case', 'Activity Diagram', 'Sequence Diagram', 'State Machine'],
      resources: ['https://www.uml-diagrams.org/'],
    },
    {
      id: 'gtd',
      name: 'GTD & Analiz Dokümantasyonu',
      priority: 'kritik',
      tools: ['Confluence', 'MS Word', 'Notion'],
      topics: ['Fonksiyonel gereksinim', 'İş kuralları', 'Kabul kriterleri', 'Traceability matrix'],
      resources: ['BABOK v3 — Gereksinim Analizi', 'IEEE 830'],
    },
    {
      id: 'agile',
      name: 'Agile / Scrum + Jira / Confluence',
      priority: 'kritik',
      tools: ['Jira', 'Confluence', 'Tempo'],
      topics: ['Sprint planning', 'Backlog refinement', 'User Story', 'DoD', 'CR yönetimi'],
      resources: ['Scrum Guide', 'Atlassian University'],
    },
    {
      id: 'mockup',
      name: 'Mockup / Wireframe',
      priority: 'onemli',
      tools: ['Figma', 'Balsamiq', 'Axure', 'draw.io'],
      topics: ['Belge yükleme ekranı', 'Onay ekranı', 'Arama/filtreleme', 'Dashboard'],
      resources: ['Figma Learn', 'Balsamiq tutorials'],
    },
    {
      id: 'sql',
      name: 'SQL & Veri Doğrulama',
      priority: 'onemli',
      tools: ['DBeaver', 'pgAdmin', 'Oracle SQL Developer'],
      topics: ['Belge durum sorguları', 'Onay süresi analizi', 'Entegrasyon log', 'Raporlama'],
      resources: ['SQLBolt', 'Mode Analytics SQL Tutorial'],
    },
    {
      id: 'uat',
      name: 'UAT Yönetimi & Kullanıcı Eğitimi',
      priority: 'onemli',
      tools: ['Jira', 'TestRail', 'Confluence'],
      topics: ['UAT planı', 'Senaryo yazımı', 'Hata takibi', 'Eğitim materyali', 'Kullanım kılavuzu'],
      resources: ['ISTQB UAT rehberi'],
    },
    {
      id: 'entegrasyon',
      name: 'Entegrasyon Doküman İnceleme',
      priority: 'onemli',
      tools: ['Postman', 'Swagger/OpenAPI'],
      topics: ['KEP API', 'E-İmza API', 'REST/SOAP', 'Veri modeli uyumu'],
      resources: ['Postman Learning Center'],
    },
    {
      id: 'kamu',
      name: 'Kamu & Kurumsal Proje Deneyimi',
      priority: 'tercih',
      tools: [],
      topics: ['5018 sayılı kanun', 'KVKK', 'Arşiv mevzuatı', 'İhale süreçleri', 'Kurumsal politika'],
      resources: ['Mevzuat.gov.tr', 'KVKK rehberleri'],
    },
    {
      id: 'isakisi',
      name: 'İş Akışı & Süreç Yönetimi',
      priority: 'tercih',
      tools: ['Bizagi', 'Camunda', 'Activiti'],
      topics: ['Süreç optimizasyonu', 'SLA tanımlama', 'Eskalasyon', 'RACI matrisi'],
      resources: ['BPM CBOK'],
    },
    {
      id: 'sdyl',
      name: 'Yazılım Geliştirme Yaşam Döngüsü',
      priority: 'onemli',
      tools: [],
      topics: ['Analiz → Geliştirme → Test → Canlıya geçiş', 'SDLC modelleri', 'Change management'],
      resources: ['BABOK v3'],
    },
  ],

  glossary: [
    { term: 'EBYS', def: 'Elektronik Belge Yönetim Sistemi — belgelerin dijital ortamda oluşturulması, onaylanması, saklanması ve imhası' },
    { term: 'DYS', def: 'Doküman Yönetim Sistemi — versiyon kontrolü, metadata, erişim yetkileri ile doküman yönetimi' },
    { term: 'E-İmza', def: '5070 sayılı kanuna göre elektronik imza — Nitelikli, Mobil, Mali Mühür türleri' },
    { term: 'KEP', def: 'Kayıtlı Elektronik Posta — yasal delil niteliği taşıyan, KEPHS üzerinden gönderilen e-posta' },
    { term: 'GTD', def: 'Gereksinim Tanımları Dokümanı — fonksiyonel/teknik gereksinimlerin resmi kaydı' },
    { term: 'UAT', def: 'Kullanıcı Kabul Testi — son kullanıcıların iş akışı bazlı testi' },
    { term: 'BPMN', def: 'Business Process Model and Notation — iş süreçlerinin standart modellemesi' },
    { term: 'CR', def: 'Change Request — gereksinim değişiklik talebi' },
    { term: 'KEPHS', def: 'KEP Hizmet Sağlayıcı — PTT KEP, TÜRKKEP gibi lisanslı sağlayıcılar' },
    { term: 'Audit Trail', def: 'Denetim izi — belge üzerindeki tüm işlem kayıtları' },
  ],

  resources: [
    { name: '5070 Sayılı E-İmza Kanunu', url: 'https://www.mevzuat.gov.tr/', type: 'Mevzuat' },
    { name: 'KEP Yönetmeliği', url: 'https://www.mevzuat.gov.tr/', type: 'Mevzuat' },
    { name: 'BABOK v3 (IIBA)', url: 'https://www.iiba.org/standards-and-resources/babok/', type: 'Kitap' },
    { name: 'draw.io (diagram)', url: 'https://app.diagrams.net/', type: 'Araç' },
    { name: 'Bizagi Modeler', url: 'https://www.bizagi.com/en/platform/modeler', type: 'Araç' },
    { name: 'Atlassian University (Jira/Confluence)', url: 'https://university.atlassian.com/', type: 'Eğitim' },
    { name: 'Figma Learn', url: 'https://help.figma.com/hc/en-us/categories/360002051613-Figma-Learn', type: 'Eğitim' },
    { name: 'SQLBolt', url: 'https://sqlbolt.com/', type: 'Eğitim' },
    { name: 'BPMN.org', url: 'https://www.bpmn.org/', type: 'Referans' },
    { name: 'İnnova Kariyer', url: 'https://www.innova.com.tr/is-ilanlari', type: 'Şirket' },
  ],
};
